
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "bws", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:9092/bws?wsdl")
public class Bws
    extends Service
{

    private final static URL BWS_WSDL_LOCATION;
    private final static WebServiceException BWS_EXCEPTION;
    private final static QName BWS_QNAME = new QName("http://ws/", "bws");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9092/bws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BWS_WSDL_LOCATION = url;
        BWS_EXCEPTION = e;
    }

    public Bws() {
        super(__getWsdlLocation(), BWS_QNAME);
    }

    public Bws(WebServiceFeature... features) {
        super(__getWsdlLocation(), BWS_QNAME, features);
    }

    public Bws(URL wsdlLocation) {
        super(wsdlLocation, BWS_QNAME);
    }

    public Bws(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BWS_QNAME, features);
    }

    public Bws(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Bws(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BanqueServicePort"), BanqueService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BWS_EXCEPTION!= null) {
            throw BWS_EXCEPTION;
        }
        return BWS_WSDL_LOCATION;
    }

}
